#!/bin/bash
 
#SBATCH -A jprocyk
#SBATCH -n 1
#SBATCH -c 4
#SBATCH -t 7-00:00               # wall time (D-HH:MM)
#SBATCH -p sulcgpu2
#SBATCH -q sulcgpu1
#SBATCH --gres=gpu:1
#SBATCH -o slurm_b3_c2pig_ge2_9_w.%j.out          # STDOUT (%j = JobId)
#SBATCH -e slurm.%j.err          # STDERR (%j = JobId)
#SBATCH --mail-type=BEGIN,END,FAIL     # notifications for job done & fail
#SBATCH --mail-user=jprocyk@asu.edu     #send to my email
#SBATCH --chdir=/scratch/jprocyk/machine_learning/phage_display_ML/rbm_torch/

source activate exmachina3

python rbm_train.py pig_ge2 ../pig_tissue/gaps_end_2_clusters/b3_c2.fasta 200 1 True

#python rbm_train.sh focus Data_Path Epochs Gpus Weights

