#!/bin/bash
 
#SBATCH -A jprocyk
#SBATCH -n 1
#SBATCH -c 2
#SBATCH -t 7-00:00               # wall time (D-HH:MM)
#SBATCH -o slurm_np3_c2.%j.out          # STDOUT (%j = JobId)
#SBATCH -e slurm.%j.err          # STDERR (%j = JobId)
#SBATCH --mail-type=BEGIN,END,FAIL     # notifications for job done & fail
#SBATCH --mail-user=jprocyk@asu.edu     #send to my email
#SBATCH --chdir=/scratch/jprocyk/machine_learning/phage_display_ML/ProteinMotifRBM/agave_submit/


source activate rbm

python RBM_trainer.py np3_c2 ../../pig_tissue/np3_c2.fasta ../../pig_tissue/trained_rbms/ 100
