#!/bin/bash
sbatch invivo0.sh
sbatch invivo1.sh
sbatch invivo2.sh
sbatch invivo3.sh
sbatch invivo4.sh
sbatch invivo5.sh
sbatch invivo6.sh
sbatch invivo7.sh
sbatch invivo8.sh
sbatch invivo9.sh
sbatch invivo10.sh
sbatch invivo11.sh
sbatch invivo12.sh
sbatch invivo13.sh
sbatch invivo14.sh
sbatch invivo15.sh
sbatch invivo16.sh
sbatch invivo17.sh
sbatch invivo18.sh
sbatch invivo19.sh
sbatch invivo20.sh
sbatch invivo21.sh
sbatch invivo22.sh
sbatch invivo23.sh
sbatch invivo24.sh
sbatch invivo25.sh
sbatch invivo26.sh
sbatch invivo27.sh
sbatch invivo28.sh
sbatch invivo29.sh
sbatch invivo30.sh
sbatch invivo31.sh
sbatch invivo32.sh
sbatch invivo33.sh
sbatch invivo34.sh
sbatch invivo35.sh
sbatch invivo36.sh
sbatch invivo37.sh
sbatch invivo38.sh
sbatch invivo39.sh
sbatch invivo40.sh
sbatch invivo41.sh
sbatch invivo42.sh
sbatch invivo43.sh
sbatch invivo44.sh
sbatch invivo45.sh
sbatch invivo46.sh
sbatch invivo47.sh
sbatch invivo48.sh
sbatch invivo49.sh
sbatch invivo50.sh
sbatch invivo51.sh
sbatch invivo52.sh
sbatch invivo53.sh
sbatch invivo54.sh
sbatch invivo55.sh
sbatch invivo56.sh
sbatch invivo57.sh
sbatch invivo58.sh
sbatch invivo59.sh
sbatch invivo60.sh
sbatch invivo61.sh
